api_version = "2025-04"

[[extensions]]
type = "pos_ui_extension"
name = "Store Credit & VIP POS"
handle = "credit-pos"
uid = "2700869e-d6a7-f20f-9330-d03688726c2da71d0c78"

  [[extensions.targeting]]
  module = "./src/index.jsx"
  target = "pos.home.tile.render"

  [[extensions.targeting]]
  module = "./src/Modal.jsx"
  target = "pos.home.modal.render"

  [[extensions.targeting]]
  module = "./src/CustomerAction.jsx"
  target = "pos.customer-details.action.render"
